# Generated by Django 4.1.6 on 2023-02-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'Doing'), (3, 'Pending'), (4, 'Done')], default=1),
        ),
    ]
